[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/nekrut/bda/blob/main/lectures/lecture3.ipynb)

# Lecture 3: Data analysis ecosystem

Language + Dataframes + Viz

First we import a module called [`random`](https://docs.python.org/3/library/random.html) which contains a number of functions for generating and working with random numbers

In [1]:
import random

## Generate a random sequence

Next, we will write a simple loop that would generate a seuqence of pre-set length:

In [2]:
seq = ''
for _ in range(100):
    seq += random.choice('ATCG')

In [3]:
seq

'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGGTCTTAGT'

## Simulate one polymerase molecule

The code below iterates through each element of a sequence `seq` (assumed to be a string containing nucleotides) and it checks if the current nucleotide is equal to 'A'. If it is, it generates a random number between 0 and 1 using the `random.random()` function.

It then checks if the random number is greater than 0.5. If it is, the code does nothing and proceeds to the next iteration. If the random number is less than or equal to 0.5, the code adds the lowercase version of the nucleotide ('a') to a string called `synthesized_strand` and then breaks out of the loop.

In every iteration of the loop, regardless of whether the nucleotide is 'A' or not, the code then adds the current nucleotide to the `synthesized_strand` string.

This means that when the current nucleotide is 'A', then the generated random number will decide whether the code will add the nucleotide 'A' or 'a' to the `synthesized_strand`, and it will break out of the loop after adding the nucleotide to the `synthesized_strand`.

In [4]:
synthesized_strand = ''

for nucleotide in seq:
    if nucleotide == 'A':
        d_or_dd = random.random()
        if d_or_dd > 0.5:
            None
        else:
            synthesized_strand += 'a'
            break
    synthesized_strand += nucleotide

This can be simplified by first removing `d_or_dd` variable:

In [5]:
synthesized_strand = ''
for nucleotide in seq:
    if nucleotide == 'A':
        if random.random() > 0.5:
            None
        else:
            synthesized_strand += 'a'
            break
    synthesized_strand += nucleotide
print(synthesized_strand)

GCCTACCGCCAa

and removing unnecessary group of `if ... else` statements:

In [6]:
synthesized_strand = ''
for nucleotide in seq:
    if nucleotide == 'A' and random.random() > 0.5:
        synthesized_strand += 'a'
        break
    synthesized_strand += nucleotide
print(synthesized_strand)

GCCTACCGCCa

finally let's make `synthesized_strand += 'a'` a bit more generic:

In [7]:
synthesized_strand = ''
for nucleotide in seq:
    if nucleotide == 'A' and random.random() > 0.5:
        synthesized_strand += nucleotide.lower()
        break
    synthesized_strand += nucleotide
print(synthesized_strand)

GCCTACCGCCa

## Simulating multiple molecules

To simulate 10 polymerase molucles we simply wrap the code from above into a `for` loop:

In [8]:
for _ in range(10):
    synthesized_strand = ''
    for nucleotide in seq:
        if nucleotide == 'A' and random.random() > 0.5:
            synthesized_strand += nucleotide.lower()
            break
        synthesized_strand += nucleotide
    print(synthesized_strand)

GCCTACCGCCa
GCCTACCGCCAAa
GCCTACCGCCAa
GCCTa
GCCTa
GCCTa
GCCTa
GCCTa
GCCTACCGCCAa
GCCTa

One problem with this code is that does not actually save the newly synthesized strand: it simply prints it. To fix this we will create a [list](https://greenteapress.com/thinkpython2/html/thinkpython2011.html) (or an array) called `new_strands` and initialize it by assigning an empty array to it:

In [9]:
new_strands = []
for _ in range(10):
    synthesized_strand = ''
    for nucleotide in seq:
        if nucleotide == 'A' and random.random() > 0.5:
            synthesized_strand += nucleotide.lower()
            break
        synthesized_strand += nucleotide
    new_strands.append(synthesized_strand)

In [10]:
new_strands

['GCCTa',
 'GCCTa',
 'GCCTACCGCCAAa',
 'GCCTa',
 'GCCTa',
 'GCCTa',
 'GCCTa',
 'GCCTACCGCCa',
 'GCCTa',
 'GCCTACCGCCa']

## Simulating multiple molecules and all nucleotides

And to repeat this for the remaining three nucleotides we will do the following crazy thing:

In [11]:
new_strands = []
for _ in range(10):
    synthesized_strand = ''
    for nucleotide in seq:
        if nucleotide == 'A' and random.random() > 0.5:
            synthesized_strand += nucleotide.lower()
            break
        synthesized_strand += nucleotide
    new_strands.append(synthesized_strand)
    
for _ in range(10):
    synthesized_strand = ''
    for nucleotide in seq:
        if nucleotide == 'C' and random.random() > 0.5:
            synthesized_strand += nucleotide.lower()
            break
        synthesized_strand += nucleotide
    new_strands.append(synthesized_strand)
    
for _ in range(10):
    synthesized_strand = ''
    for nucleotide in seq:
        if nucleotide == 'G' and random.random() > 0.5:
            synthesized_strand += nucleotide.lower()
            break
        synthesized_strand += nucleotide
    new_strands.append(synthesized_strand)
    
for _ in range(10):
    synthesized_strand = ''
    for nucleotide in seq:
        if nucleotide == 'T' and random.random() > 0.5:
            synthesized_strand += nucleotide.lower()
            break
        synthesized_strand += nucleotide
    new_strands.append(synthesized_strand)

In [12]:
len(new_strands)

40

Repeating the same code four times is just plain stupid so instead we will write a function called `polymerase`. Here we need to worry about the scope of variables.  The scope of a variable refers to the regions of the code where the variable can be accessed or modified. Variables that are defined within a certain block of code (such as a function or a loop) are said to have a *local* scope, meaning that they can only be accessed within that block of code. Variables that are defined outside of any block of code are said to have a *global* scope, meaning that they can be accessed from anywhere in the code.

In most programming languages, a variable defined within a function has a local scope, and it can only be accessed within that function. If a variable with the same name is defined outside the function, it will have a global scope and can be accessed from anywhere in the code. However, if a variable with the same name is defined within the function, it will take precedence over the global variable and will be used within the function.

There are also some languages that have block scope, where a variable defined within a block (such as an if statement or a for loop) can only be accessed within that block and not outside of it.

In Python, variables defined in the main module have global scope and can be accessed from any function or module. Variables defined within a function have local scope, and they can only be accessed within that function. Variables defined within a loop or a block, can be accessed only within the scope of the loop or block.

In [13]:
def ddN(number_of_iterations, template, base, ddN_ratio):
    new_strands = []
    for _ in range(number_of_iterations):
        synthesized_strand = ''
        for nucleotide in template:
            if nucleotide == base and random.random() > ddN_ratio:
                synthesized_strand += nucleotide.lower()
                break
            synthesized_strand += nucleotide
        new_strands.append(synthesized_strand)
    return(new_strands)

In [14]:
ddN(10,seq,'A',0.5)

['GCCTa',
 'GCCTa',
 'GCCTACCGCCAa',
 'GCCTACCGCCAa',
 'GCCTa',
 'GCCTa',
 'GCCTa',
 'GCCTACCGCCAa',
 'GCCTACCGCCa',
 'GCCTACCGCCa']

To execute this function on all four types of ddNTPs with need to wrap it in a `for` loop iterating over the four possibilies:

In [15]:
for nt in 'ATCG':
    ddN(10,seq,nt,0.5)

## A bit about [lists](https://greenteapress.com/thinkpython2/html/thinkpython2011.html)

To store the sequences being generated in the previous loop we will create and initialize a list called `seq_run`:

In [16]:
seq_run = []
for nt in 'ATCG':
    seq_run.append(ddN(10,seq,nt,0.5))

you will see that the seq run is a two-dimensional list:

In [17]:
seq_run

[['GCCTa',
  'GCCTa',
  'GCCTACCGCCAa',
  'GCCTa',
  'GCCTa',
  'GCCTa',
  'GCCTa',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAa',
  'GCCTa',
  'GCCTa'],
 ['GCCt',
  'GCCt',
  'GCCTACCGCCAAACCGCCt',
  'GCCTACCGCCAAACCGCCTCCAGTGt',
  'GCCTACCGCCAAACCGCCt',
  'GCCTACCGCCAAACCGCCTCCAGTGTt',
  'GCCt',
  'GCCTACCGCCAAACCGCCTCCAGt',
  'GCCTACCGCCAAACCGCCTCCAGt',
  'GCCt'],
 ['Gc',
  'Gc',
  'Gc',
  'GCCTACCGCc',
  'GCCTAc',
  'GCCTAc',
  'GCCTACc',
  'GCc',
  'GCc',
  'GCCTACCGCCAAAc'],
 ['GCCTACCg',
  'GCCTACCg',
  'GCCTACCGCCAAACCg',
  'g',
  'g',
  'GCCTACCGCCAAACCg',
  'g',
  'g',
  'g',
  'GCCTACCg']]

as you will read in your next home assignment list elements can be addressed by "index". The first element has number 0:

In [18]:
seq_run[0]

['GCCTa',
 'GCCTa',
 'GCCTACCGCCAa',
 'GCCTa',
 'GCCTa',
 'GCCTa',
 'GCCTa',
 'GCCTACCGCCAAACCGCCTCCAGTGTTACAAa',
 'GCCTa',
 'GCCTa']

## A bit about [dictionaries](https://greenteapress.com/thinkpython2/html/thinkpython2012.html)

Another way to store these data is in a dictionary, which is a collection of key:value pairs where a key and value can be anything:

In [19]:
seq_run = {}
for nt in 'ATCG':
    seq_run[nt] = ddN(10,seq,nt,0.90)

In [20]:
seq_run

{'A': ['GCCTACCGCCAAACCGCCTCCAGTGTTa',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAa',
  'GCCTa',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAa',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGGTCTTAGT',
  'GCCTACCGCCAa',
  'GCCTa',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGGTCTTAGT',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCa',
  'GCCTACCGCCAAa'],
 'T': ['GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTt',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTt',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCt',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTt',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACt',
  'GCCTACCGCCAAACCGCCTCCAGt',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGGt',
  'GCCTACCGCCAAACCGCCTCCAGTGt',
  'GCCt',
  'GCCTACCGCCAAACCGCCTCCAGt'],
 'C': ['GCCTACCGCCAAACCGCCTCCAGTGTTAc',
  'GCCTACCGCCAAACc',
  'GCCTACCGCCAAAc',
  'GCCTACCGCCAAAc',
  'GCCTACCGCc',
  'GCCTACCGCCAAAc',
  'GCCTACCGCCAAACCGc',
  'GCc',
  'GCCTACCGCc',
  'GCc'],
 'G': ['GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGg',
  'GCCTACCGCCAAACCGCCTCCAg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCg',
  'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGg',
  'GCCTACCg']}

dictionary elements can be retrieved using a key:

In [21]:
seq_run['A']

['GCCTACCGCCAAACCGCCTCCAGTGTTa',
 'GCCTACCGCCAAACCGCCTCCAGTGTTACAAa',
 'GCCTa',
 'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAa',
 'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGGTCTTAGT',
 'GCCTACCGCCAa',
 'GCCTa',
 'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCAACAGACTGAGTAGTCGAGGTCTTAGT',
 'GCCTACCGCCAAACCGCCTCCAGTGTTACAAATCAGGACTTCGCTTAGTACAGCTCTGTAGGCGTGTCAAGTCa',
 'GCCTACCGCCAAa']

## Drawing a sequencing gel

Now that we can simulate and store newly synthesized sequencing strands terminated with ddNTPs let us try to draw a realistic representation of the sequencing gel. For this we will use several componenets that will be discussed in a much greated deatil in the upcoming lectures. These componenets are:

- [`pandas`](https://pandas.pydata.org/) - a dataframe manipulation tool
- [`altair`](https://altair-viz.github.io/) - a statistical visualization library built on top of `vega-light` visualization grammar

These two libraries will be used in almost all lectures concerning Python in this class.

[Gel electophoresis](https://en.wikipedia.org/wiki/Gel_electrophoresis) separates molecules based on mass, shape, or charge. In case of DNA all molecules are universally negatively charges and thus will always migrate to (+) electrode. All our molecules are linear single stranded pieces (our gel is *denaturing*) and so the only physical/chemical characteristic that disnguished them is *length*. Therefore the first thing we will do is to convert our sequecnes into their lengths. For this we will initialize a new dictionary called `seq_lengths`:

In [22]:
seq_lengths = {'base':[],'length':[]}
for key in seq_run.keys():
    for sequence in seq_run[key]:
        seq_lengths['base'].append(key)
        seq_lengths['length'].append(len(sequence))

In [23]:
seq_lengths

{'base': ['A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'T',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'G',
  'G',
  'G',
  'G',
  'G',
  'G',
  'G',
  'G',
  'G',
  'G'],
 'length': [28,
  32,
  5,
  75,
  100,
  12,
  5,
  100,
  74,
  13,
  41,
  41,
  55,
  41,
  40,
  24,
  94,
  26,
  4,
  24,
  29,
  15,
  14,
  14,
  10,
  14,
  17,
  3,
  10,
  3,
  78,
  43,
  53,
  78,
  37,
  23,
  53,
  43,
  93,
  8]}

now let's import `pandas`:

In [24]:
import pandas as pd

and inject `seq_lengths` into a pandas *dataframe*:

In [25]:
sequences = pd.DataFrame(seq_lengths)

it looks pretty:

In [26]:
sequences

   base  length
0     A      28
1     A      32
2     A       5
3     A      75
4     A     100
5     A      12
6     A       5
7     A     100
8     A      74
9     A      13
10    T      41
11    T      41
12    T      55
13    T      41
14    T      40
15    T      24
16    T      94
17    T      26
18    T       4
19    T      24
20    C      29
21    C      15
22    C      14
23    C      14
24    C      10
25    C      14
26    C      17
27    C       3
28    C      10
29    C       3
30    G      78
31    G      43
32    G      53
33    G      78
34    G      37
35    G      23
36    G      53
37    G      43
38    G      93
39    G       8

In our data there is a number of DNA fragments that have identical length (just look at the dataframe above). We can condense these by grouping dataframe entries first by nucleotide (`['base']`) and then by length (`['length']`). For each group we will then compute `count` and put it into a new column named, unsurprisngly, `count`:

In [27]:
sequences_grouped_by_length = sequences.groupby(
    ['base','length']
).agg(
    count=pd.NamedAgg(
        column='length',
        aggfunc='count'
    )
).reset_index()

In [28]:
sequences_grouped_by_length

   base  length  count
0     A       5      2
1     A      12      1
2     A      13      1
3     A      28      1
4     A      32      1
5     A      74      1
6     A      75      1
7     A     100      2
8     C       3      2
9     C      10      2
10    C      14      3
11    C      15      1
12    C      17      1
13    C      29      1
14    G       8      1
15    G      23      1
16    G      37      1
17    G      43      2
18    G      53      2
19    G      78      2
20    G      93      1
21    T       4      1
22    T      24      2
23    T      26      1
24    T      40      1
25    T      41      3
26    T      55      1
27    T      94      1

The following chart is created using the `alt.Chart()` function and passing the data as an argument. The `mark_tick()` function is used to create a tick chart with a thickness of 4 pixels.

The chart is encoded with two main axis:

- y-axis which represents the length of the data and it is encoded by the `'length'` field of the data.
- x-axis which represents the base of the data and it is encoded by the `'base'` field of the data.
The chart also encodes a color, it encodes the `'count'` field of the data and it sets the legend to `None` and it uses the `'greys'` scale from the Altair library.

Finally, the chart properties are set to a width of 100 pixels and a height of 800 pixels.

In [29]:
import altair as alt
alt.Chart(sequences_grouped_by_length).mark_tick(thickness=4).encode(
    y = alt.Y('length:Q'),
    x = alt.X('base'),
    color=alt.Color('count:Q',legend=None,
                    scale=alt.Scale(scheme="greys"))
).properties(
    width=100,
    height=800)

alt.Chart(...)

And here is a color version of the same graph using just one line of the gel:

In [30]:
import altair as alt
alt.Chart(sequences_grouped_by_length).mark_tick(thickness=4).encode(
    y = alt.Y('length:Q'),
    color=alt.Color('base:N',#legend=None,
                    scale=alt.Scale(scheme="set1"))
).properties(
    width=20,
    height=800)

alt.Chart(...)

In [31]:
# Generate random sequences

seq = ''
for _ in range(300):
    seq += random.choice('ATCG')

## Putting everything together

In [32]:
seq

'TTTCGACCGAGTGGACTTCGTGTACAGAGCAAAACCAGCTGAGGACGCGTGAACCCACTGCCCGTGTGCGCGCGGTCTTCACACATAAATTGCTGAGATCCTTGCACCCCGGTATGACCAGCGTCCCACGTGCCTGTCATACTATAATGTGTATAGAATTTACAGTGGCATAAGCTATCCAGACAAGTGCCGTCGCATTCCACCTGCACGGGTTATGTCCATGGTTATATTCCAAGAAAAGATGATGGAACATATTGGACACAATGTGATTGAGTCCTTCCTGGGCGAAGGTGTTCTATG'

In [33]:
# Function silulating a single run of a single polymerase molecule

def ddN(number_of_iterations, template, base, ddN_ratio):
    new_strands = []
    for _ in range(number_of_iterations):
        synthesized_strand = ''
        for nucleotide in template:
            if nucleotide == base and random.random() > ddN_ratio:
                synthesized_strand += nucleotide.lower()
                break
            synthesized_strand += nucleotide
        new_strands.append(synthesized_strand)
    return(new_strands)

In [34]:
# Generating simulated sequencing run

seq_run = {}
for nt in 'ATCG':
    seq_run[nt] = ddN(100000,seq,nt,0.95)

In [35]:
# Computing lengths

seq_lengths = {'base':[],'length':[]}
for key in seq_run.keys():
    for sequence in seq_run[key]:
        seq_lengths['base'].append(key)
        seq_lengths['length'].append(len(sequence))

In [36]:
# Converting dictionaty into Pandas dataframe

sequences = pd.DataFrame(seq_lengths)

In [37]:
# Grouping by nucleotide and length

sequences_grouped_by_length = sequences.groupby(
    ['base','length']
).agg(
    count=pd.NamedAgg(
        column='length',
        aggfunc='count'
    )
).reset_index()

In [38]:
# Plotting (note the quadratic scale for realism)

import altair as alt
alt.Chart(sequences_grouped_by_length).mark_tick(thickness=4).encode(
    y = alt.Y('length:Q',scale=alt.Scale(type='sqrt')),
    x = alt.X('base'),
    color=alt.Color('count:Q',legend=None,
                    scale=alt.Scale(type='log',scheme="greys")),
    tooltip='count:Q'
).properties(
    width=100,
    height=800)

alt.Chart(...)

In [39]:
# Plotting using color

import altair as alt
alt.Chart(sequences_grouped_by_length).mark_tick(thickness=4).encode(
    y = alt.Y('length:Q',scale=alt.Scale(type="sqrt")),
    color=alt.Color('base:N',#legend=None,
                    scale=alt.Scale(scheme="set1")),
    opacity=alt.Opacity('count:N',legend=None),
    tooltip='count:Q'
).properties(
    width=20,
    height=800)

alt.Chart(...)

## Homework

----

Chapters [1](https://greenteapress.com/thinkpython2/html/thinkpython2002.html), [2](https://greenteapress.com/thinkpython2/html/thinkpython2003.html), [3](https://greenteapress.com/thinkpython2/html/thinkpython2004.html) from "Think Python"